### ISSUE TITLE
parametric constructor warning

### ISSUE THREAD

**Issue by t-bltg** [Suzhou-Tongyuan/ObjectOriented.jl#10]
The following leaves a warning, although the result is correct:
```julia
julia> @oodef struct Foo{F}
  x::F
  function new()
    @mk x = F(1)
  end
end
WARNING: method definition for Foo at REPL[4]:3 declares type variable F but does not use it.

julia> f = Foo{Float64}()
julia> f.x
1.0
```

**Comment by thautwarm** [comment]
This is generally not achievable due to the lack of scope analysis tool for Julia metaprogramming.
Anyway, I created a partial fix for this at https://github.com/Suzhou-Tongyuan/ObjectOriented.jl/pull/14 .

Please comment if any idea.
